version: '2.2'

services:

    backend:
        build:
            dockerfile: ./backend.dockerfile
            context: ./backend
        image: node
        container_name: backend
        expose: 
            - "3333" 
        networks: 
            - network-instarocket

    frontend:
        build:
            dockerfile: ./frontend.dockerfile
            context: ./frontend
        image: node
        container_name: frontend
        expose: 
            - "3000"
        networks: 
            - network-instarocket
        depends_on: 
            - "backend"

    mobile:
        build:
            dockerfile: ./mobile.dockerfile
            context: ./instarocket
        image: node
        container_name: mobile
        networks: 
            - network-instarocket
        depends_on: 
            - "backend"
            - "frontend"

networks:
    network-instarocket:
        driver: bridge